import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Queryclientprovider } from "@/Providers/Queryclientprovider";
import { ToastContainer } from "react-toastify";
import AuthContextProvider from "@/context/context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Facebook Clone",
  description: "Generated by create next app",
};
// Create a client

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
           <Queryclientprovider>
             <ToastContainer/>
             <AuthContextProvider>
                  {children}
              </AuthContextProvider>

           
           </Queryclientprovider>
           
              
           

      

      </body>
    </html>
  );
}
